### ISSUE TITLE
Implicit empty needs

### ISSUE THREAD

**Issue by Beanow** [fluture-js/booture#3]
A bootstrapper object currently requires a needs field or it will crash with:

```
TypeError: Cannot read property 'every' of undefined
    at pred (.../node_modules/booture/index.js:24:39)
```

I think the needs field can be made optional so it's the equivalent of adding `needs: []`.

_(Excuse the nitpicking, commenting with some points that I run into porting an existing project to booture as I run into them.)_

**Comment by Avaq** [comment]
I prefer to tackle this problem in a way that doesn't make the Bootstrapper type more complex.

Maybe the solution can be twofold:

1. Provide a better TypeError message when `bootstrap` is not strictly called with an `Array (Bootstrapper a b)`
2. Provide a function like `independent :: Name -> Hook (Future Error a) b
 -> Bootstrapper a b`, so you can do:
    ```js
    const configBootstrapper = independent ('config') (hook (acquire) (dispose));

**Comment by Beanow** [comment]
I think that trades internal complexity for user complexity. Having to explicitly specify a different type to avoid `needs: []` seems to defeat the purpose. For me the goal would be to have a consistent and easy to read service specification.
